language: java
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.m2
jdk:
- oraclejdk8
+script: mvn clean checkstyle:checkstyle findbugs:findbugs install

install: true
script: ./travis/build.sh
notifications:
  irc: "irc.rizon.net#runelite"

    